name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1rKUYgoG3nTMae2wzG7xPhlvmNr_3tpt6XL58jztRdWbhuDTP
        USER_PASS: qazwsxedc
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 2h
